services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_BASE_URL: http://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
