sonar.projectKey=your-org_text-analyzer-cicd
sonar.organization=your-org
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend/app
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=frontend/src/**/*.test.js,backend/tests/**/*.py
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
